name: testing

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: ["v1.x"]
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.node-version }}
      - run: deno test --parallel --coverage && deno coverage --lcov cov > cov.lcov
      - name: Upload coverage to Coveralls.io
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.ACTION_TOKEN }}
          path-to-lcov: cov.lcov
